modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Virtuoel/Discarnate/issues"
[[mods]]
modId="discarnate"
version="${file.jarVersion}"
displayName="Discarnate"
displayURL="https://www.curseforge.com/minecraft/mc-mods/discarnate/"
logoFile="assets/discarnate/icon.png"
authors="Virtuoel"
description='''
Let spirits control your body to do tasks.
'''
[[mixins]]
config="discarnate.mixins.json"
